
import ez
warn=ez.JDict()

# warn.update({'basic.R':[271]})
# warn.update({'basic.R':[272]})
# warn.update({'basic.R':[273]})
# warn.update({'basic.R':[278]})
# warn.update({'basic.R':[279]})
# warn.update({'basic.R':[280]})
# warn.update({'basic.R':[285]})
# warn.update({'basic.R':[286]})
# warn.update({'basic.R':[287]})
# warn.update({'basic.R':[292]})
# warn.update({'basic.R':[293]})
# warn.update({'basic.R':[294]})
# warn.update({'basic.R':[321]})
# warn.update({'basic.R':[330]})
# warn.update({'basic.R':[331]})
# warn.update({'basic.R':[338]})
# warn.update({'basic.R':[339]})
# warn.update({'basic.R':[340]})
# warn.update({'basic.R':[370]})
# warn.update({'basic.R':[428]})
# warn.update({'basic.R':[442]})
# warn.update({'basic.R':[464]})
# warn.update({'basic.R':[465]})
# warn.update({'basic.R':[466]})
# warn.update({'basic.R':[479]})
# warn.update({'basic.R':[480]})
# warn.update({'basic.R':[481]})
# warn.update({'basic.R':[498]})
# warn.update({'basic.R':[499]})
# warn.update({'basic.R':[500]})
# warn.update({'basic.R':[517]})
# warn.update({'basic.R':[520]})
# warn.update({'basic.R':[533]})
# warn.update({'basic.R':[534]})
# warn.update({'basic.R':[535]})
# warn.update({'basic.R':[558]})
# warn.update({'basic.R':[559]})
# warn.update({'basic.R':[583]})
# warn.update({'frame.R':[98]})
# warn.update({'frame.R':[148]})
# warn.update({'frame.R':[153]})
# warn.update({'frame.R':[195]})
# warn.update({'frame.R':[196]})
# warn.update({'frame.R':[216]})
# warn.update({'frame.R':[217]})
# warn.update({'frame.R':[218]})
# warn.update({'frame.R':[242]})
# warn.update({'frame.R':[244]})
# warn.update({'frame.R':[263]})
# warn.update({'frame.R':[267]})
# warn.update({'frame.R':[293]})
# warn.update({'frame.R':[458]})
# warn.update({'frame.R':[514]})
# warn.update({'frame.R':[544]})
# warn.update({'frame.R':[1199]})
# warn.update({'frame.R':[1218]})
# warn.update({'frame.R':[1238]})
# warn.update({'frame.R':[1254]})
# warn.update({'frame.R':[1270]})
# warn.update({'frame.R':[1473]})
# warn.update({'io.R':[30]})
# warn.update({'io.R':[55]})
# warn.update({'io.R':[56]})
# warn.update({'io.R':[174]})
# warn.update({'io.R':[176]})
# warn.update({'io.R':[253]})
# warn.update({'io.R':[477]})
# warn.update({'io.R':[478]})
# warn.update({'io.R':[479]})
# warn.update({'io.R':[486]})
# warn.update({'io.R':[487]})
# warn.update({'io.R':[488]})
# warn.update({'os.R':[10]})
# warn.update({'os.R':[11]})
# warn.update({'os.R':[12]})
# warn.update({'os.R':[18]})
# warn.update({'os.R':[19]})
# warn.update({'os.R':[20]})
# warn.update({'os.R':[83]})
# warn.update({'os.R':[106]})
# warn.update({'os.R':[107]})
# warn.update({'os.R':[108]})
# warn.update({'os.R':[114]})
# warn.update({'os.R':[115]})
# warn.update({'os.R':[116]})
# warn.update({'os.R':[122]})
# warn.update({'os.R':[123]})
# warn.update({'os.R':[124]})
# warn.update({'os.R':[147]})
# warn.update({'os.R':[148]})
# warn.update({'os.R':[165]})
# warn.update({'os.R':[166]})
# warn.update({'os.R':[182]})
# warn.update({'os.R':[183]})
# warn.update({'os.R':[184]})
# warn.update({'os.R':[190]})
# warn.update({'os.R':[191]})
# warn.update({'os.R':[192]})
# warn.update({'os.R':[198]})
# warn.update({'os.R':[199]})
# warn.update({'os.R':[200]})
# warn.update({'os.R':[212]})
# warn.update({'os.R':[213]})
# warn.update({'os.R':[247]})
# warn.update({'os.R':[248]})
# warn.update({'os.R':[254]})
# warn.update({'os.R':[255]})
# warn.update({'os.R':[256]})
# warn.update({'os.R':[262]})
# warn.update({'os.R':[264]})
# warn.update({'os.R':[271]})
# warn.update({'os.R':[273]})
# warn.update({'os.R':[281]})
# warn.update({'os.R':[282]})
# warn.update({'os.R':[283]})
# warn.update({'os.R':[289]})
# warn.update({'os.R':[290]})
# warn.update({'os.R':[291]})
# warn.update({'os.R':[297]})
# warn.update({'os.R':[298]})
# warn.update({'os.R':[306]})
# warn.update({'os.R':[307]})
# warn.update({'os.R':[308]})
# warn.update({'os.R':[332]})
# warn.update({'os.R':[333]})
# warn.update({'os.R':[334]})
# warn.update({'os.R':[340]})
# warn.update({'os.R':[341]})
# warn.update({'os.R':[342]})
# warn.update({'os.R':[348]})
# warn.update({'os.R':[349]})
# warn.update({'os.R':[350]})
# warn.update({'os.R':[356]})
# warn.update({'os.R':[357]})
# warn.update({'os.R':[358]})
# warn.update({'os.R':[364]})
# warn.update({'os.R':[365]})
# warn.update({'os.R':[397]})
# warn.update({'os.R':[398]})
# warn.update({'os.R':[408]})
# warn.update({'os.R':[409]})
# warn.update({'os.R':[425]})
# warn.update({'os.R':[426]})
# warn.update({'os.R':[427]})
# warn.update({'os.R':[439]})
# warn.update({'os.R':[440]})
# warn.update({'os.R':[441]})
# warn.update({'os.R':[453]})
# warn.update({'os.R':[454]})
# warn.update({'os.R':[455]})
# warn.update({'os.R':[463]})
# warn.update({'os.R':[464]})
# warn.update({'os.R':[465]})
# warn.update({'os.R':[471]})
# warn.update({'os.R':[472]})
# warn.update({'os.R':[485]})
# warn.update({'os.R':[486]})
# warn.update({'os.R':[513]})
# warn.update({'os.R':[514]})
# warn.update({'os.R':[565]})
# warn.update({'os.R':[566]})
# warn.update({'plot.R':[141]})
# warn.update({'plot.R':[190]})
# warn.update({'plot.R':[300]})
# warn.update({'plot.R':[301]})
# warn.update({'plot.R':[316]})
# warn.update({'plot.R':[317]})
# warn.update({'plot.R':[331]})
# warn.update({'plot.R':[332]})
# warn.update({'plot.R':[342]})
# warn.update({'plot.R':[343]})
# warn.update({'plot.R':[355]})
# warn.update({'plot.R':[356]})
# warn.update({'plot.R':[439]})
# warn.update({'plot.R':[601]})
# warn.update({'plot.R':[754]})
# warn.update({'plot.R':[893]})
# warn.update({'plot.R':[1005]})
# warn.update({'plot.R':[1093]})
# warn.update({'plot.R':[1126]})
# warn.update({'plot.R':[1145]})
# warn.update({'plot.R':[1146]})
# warn.update({'plot.R':[1173]})
# warn.update({'plot.R':[1273]})
# warn.update({'plot.R':[1499]})
# warn.update({'plot.R':[1706]})
# warn.update({'plot.R':[1927]})
# warn.update({'plot.R':[2004]})
# warn.update({'stats.R':[6]})
# warn.update({'stats.R':[8]})
# warn.update({'stats.R':[9]})
# warn.update({'stats.R':[56]})
# warn.update({'stats.R':[310]})
# warn.update({'stats.R':[311]})
# warn.update({'stats.R':[365]})
# warn.update({'stats.R':[433]})
# warn.update({'stats.R':[502]})

warn.update({'basic.R':[288]})
warn.update({'basic.R':[293]})
warn.update({'basic.R':[298]})
warn.update({'basic.R':[303]})
warn.update({'basic.R':[332]})
warn.update({'basic.R':[341]})
warn.update({'basic.R':[348]})
warn.update({'basic.R':[378]})
warn.update({'basic.R':[436]})
warn.update({'basic.R':[470]})
warn.update({'basic.R':[483]})
warn.update({'basic.R':[500]})
warn.update({'basic.R':[519]})
warn.update({'basic.R':[532]})
warn.update({'basic.R':[581]})
warn.update({'frame.R':[157]})
warn.update({'frame.R':[286]})
warn.update({'frame.R':[450]})
warn.update({'frame.R':[506]})
warn.update({'frame.R':[535]})
warn.update({'frame.R':[1192]})
warn.update({'frame.R':[1211]})
warn.update({'frame.R':[1230]})
warn.update({'frame.R':[1245]})
warn.update({'frame.R':[1261]})
warn.update({'frame.R':[1470]})
warn.update({'io.R':[32]})
warn.update({'io.R':[176]})
warn.update({'io.R':[177]})
warn.update({'io.R':[254]})
warn.update({'io.R':[478]})
warn.update({'io.R':[484]})
warn.update({'os.R':[10]})
warn.update({'os.R':[15]})
warn.update({'os.R':[77]})
warn.update({'os.R':[99]})
warn.update({'os.R':[104]})
warn.update({'os.R':[109]})
warn.update({'os.R':[131]})
warn.update({'os.R':[147]})
warn.update({'os.R':[162]})
warn.update({'os.R':[167]})
warn.update({'os.R':[172]})
warn.update({'os.R':[183]})
warn.update({'os.R':[216]})
warn.update({'os.R':[221]})
warn.update({'os.R':[226]})
warn.update({'os.R':[227]})
warn.update({'os.R':[233]})
warn.update({'os.R':[234]})
warn.update({'os.R':[240]})
warn.update({'os.R':[245]})
warn.update({'os.R':[280]})
warn.update({'os.R':[285]})
warn.update({'os.R':[290]})
warn.update({'os.R':[295]})
warn.update({'os.R':[355]})
warn.update({'os.R':[366]})
warn.update({'os.R':[377]})
warn.update({'os.R':[384]})
warn.update({'plot.R':[146]})
warn.update({'plot.R':[195]})
warn.update({'plot.R':[307]})
warn.update({'plot.R':[322]})
warn.update({'plot.R':[336]})
warn.update({'plot.R':[441]})
warn.update({'plot.R':[603]})
warn.update({'plot.R':[756]})
warn.update({'plot.R':[895]})
warn.update({'plot.R':[1007]})
warn.update({'plot.R':[1094]})
warn.update({'plot.R':[1146]})
warn.update({'plot.R':[1173]})
warn.update({'plot.R':[1498]})
warn.update({'plot.R':[1704]})
warn.update({'plot.R':[1924]})
warn.update({'plot.R':[2000]})
warn.update({'stats.R':[6]})
warn.update({'stats.R':[7]})
warn.update({'stats.R':[54]})
warn.update({'stats.R':[360]})
warn.update({'stats.R':[427]})
warn.update({'stats.R':[495]})

ez.cd('/Users/jerry/Dropbox/Apps/RStudio/ezmisc/R')
for file, il in warn.iteritems():
    f = open(file,"r")
    lines = f.readlines()
    f.close()
    f = open(file,"w")
    for l in range(1,len(lines)+1):
      if l not in il:
        f.write(lines[l-1])
    f.close()
